### ISSUE TITLE
Not supported by Titanium SDK 3.5.0

### ISSUE THREAD

**Issue by andersdp** [iotashan/TiTouchImageView#6]
I don't know what it takes but could it be?

**Comment by iotashan** [comment]
Did you try it, or did you just post here after seeing a warning message? :)

**Comment by andersdp** [comment]
I posted after seeing my project failed to built :) And because I don't know how to fix it :)

**Comment by iotashan** [comment]
I just released 1.0.1 which I recompiled with Ti 3.5.1.GA. Tested, works!

**Comment by andersdp** [comment]
Great, tanx :)
