### ISSUE TITLE
Could not find all required Titanium Modules

### ISSUE THREAD

**Issue by monotv** [iotashan/TiTouchImageView#8]
I use Titanium SDK 3.5.1.GA.

The module is called in the tiapp.xml like so:
`<module platform="android">org.iotashan.TiTouchImageView</module>`

It resides under this path: `/modules/android/org.iotashan.titouchimageview/1.0.2/`

I am getting this error:
```
[ERROR] Could not find all required Titanium Modules:
[ERROR]    id: org.iotashan.TiTouchImageView     version: latest         platform: android       deploy-type: test
```
I tried writing the directory name with uppercase/lowercase capitalization, updated the SDK from 3.5.0 to 3.5.1, nothing worked. Your help would be appreciated.

**Comment by idkfa46** [comment]
Here the same problem with SDK 3.3.0 . 
Someone solved it?

Regards, Matteo

**Comment by iotashan** [comment]
You have an understandable case-sensitive typo in your tiapp.xml file. Per the README, you need to use `<module platform="android">org.iotashan.titouchimageview</module>` there, but use `require('org.iotashan.TiTouchImageView')` in your code.
