### ISSUE TITLE
SDK 3.3.0

### ISSUE THREAD

**Issue by idkfa46** [iotashan/TiTouchImageView#9]
Is this module compatible to SDK 3.3.0?
I can correctly install it by gittio but Appcelerator Studio give me an allert: "SKD 3.3.0 not suporter"

Regards, 
Matteo

**Comment by iotashan** [comment]
That's because the module is built with Ti 3.5.1

`minsdk: 3.5.1.GA`

You're of course welcome to try compiling it yourself against unsupported SDKs, but you probably should be working on updating anyway.

**Comment by idkfa46** [comment]
I'm builded it up with with SDK 3.5.1.GA but nothing change....

![screen](https://cloud.githubusercontent.com/assets/8988963/8461466/1a1a8fc6-202d-11e5-8918-f46de598b98d.png)

here is the error when I try to compile:
 C:\Program Files (x86)\nodejs\node.exe C:\Users\Matteo\.appcelerator\install\4.0.2\package\node_modules\appc-cli-titanium\node_modules\titanium\bin\titanium build --platform android --log-level trace --sdk 3.5.1.GA --project-dir C:\Users\Matteo\Documents\Appcelerator_Studio_Workspace\eligePic --target device --android-sdk C:\android-sdk-win --device-id 4300d60647f0800f --skip-js-minify --no-colors --no-progress-bars --no-prompt --prompt-type socket-bundle --prompt-port 63530 --plugin-paths C:\Users\Matteo\.appcelerator\install\4.0.2\package\node_modules --config-file C:\Users\Matteo\AppData\Local\Temp\build-1435773368640.json --no-banner
[ERROR] Application Installer abnormal process termination. Process exit value was 1

Any suggestion about it?

Regards, Matteo

**Comment by iotashan** [comment]
You forgot to fix your other problem... in tiapp.xml you need to use all lower case for the module id.

**Comment by idkfa46** [comment]
Thanks! ;)
